FROM node:20-alpine AS build
WORKDIR /app
COPY ticket-system-frontend/package*.json ./
RUN npm install
COPY ticket-system-frontend ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist/ticket-system-frontend/browser /usr/share/nginx/html
COPY ticket-system-frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY ticket-system-frontend/public/config.js /usr/share/nginx/html/config.js
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
